--STATIC DATA SQL (Don't edit this file)

-- Insert Into CODE_TYPE_ENTITY

----------------------------- GENDER ---------------------------------------------
WITH new_code_type_entity_gender AS (
INSERT INTO
CODE_TYPE_ENTITY
( CODE_TYPE_ID, CODE_TYPE_KEY, CODE_TYPE_SHORT_DESCRIPTION, CODE_TYPE_DESCRIPTION, CODE_TYPE_IS_AVAILABLE, CODE_TYPE_PRIORITY,
CODE_TYPE_CREATED_BY, CODE_TYPE_UPDATED_BY, CODE_TYPE_CREATED_DATE_TIME, CODE_TYPE_MODIFIED_DATE_TIME)
VALUES
( NEXTVAL('CODE_TYPE_ENTITY_SEQ'), 'GENDER', 'Gender', 'Gender', true, 1,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
returning CODE_TYPE_ID)

INSERT INTO
CODE_ENTITY
(CODE_ID, CODE_CODE_TYPE_ID, CODE_KEY, CODE_SHORT_DESCRIPTION, CODE_DESCRIPTION, CODE_IS_AVAILABLE, CODE_PRIORITY,
CODE_CREATED_BY, CODE_UPDATED_BY, CODE_CREATED_DATE_TIME, CODE_MODIFIED_DATE_TIME)
VALUES
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_gender) ,'MALE', 'Male', 'Male', true, 1,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_gender) ,'FEMALE', 'Female', 'Female', true, 2,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_gender) ,'PNTS', 'Prefer not to say', 'Prefer not to say', true, 3,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_gender) ,'OTHER', 'Other', 'Other', true, 4,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


----------------------------- TITLE ---------------------------------------------
WITH new_code_type_entity_title AS (
INSERT INTO
CODE_TYPE_ENTITY
( CODE_TYPE_ID, CODE_TYPE_KEY, CODE_TYPE_SHORT_DESCRIPTION, CODE_TYPE_DESCRIPTION, CODE_TYPE_IS_AVAILABLE, CODE_TYPE_PRIORITY,
CODE_TYPE_CREATED_BY, CODE_TYPE_UPDATED_BY, CODE_TYPE_CREATED_DATE_TIME, CODE_TYPE_MODIFIED_DATE_TIME)
VALUES
( NEXTVAL('CODE_TYPE_ENTITY_SEQ'), 'TITLE', 'Title', 'Title', true, 2,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
returning CODE_TYPE_ID)

INSERT INTO
CODE_ENTITY
(CODE_ID, CODE_CODE_TYPE_ID, CODE_KEY, CODE_SHORT_DESCRIPTION, CODE_DESCRIPTION, CODE_IS_AVAILABLE, CODE_PRIORITY,
CODE_CREATED_BY, CODE_UPDATED_BY, CODE_CREATED_DATE_TIME, CODE_MODIFIED_DATE_TIME)
VALUES
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_title) ,'MR', 'MR', 'Mister', true, 1,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_title) ,'MS', 'MS', 'Miz', true, 2,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_title) ,'MRS', 'MRS', 'Miziz', true, 3,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( NEXTVAL('CODE_ENTITY_SEQ'), (select CODE_TYPE_ID from new_code_type_entity_title) ,'MISS', 'MISS', 'Miss', true, 4,
'ENGINE', 'ENGINE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

